- SwinUNETR/BRATS21/README.md
- UNETR/BTCV/README.md
This PR adds Swin UNETR placeholder repository. 
Signed-off-by: ahatamizadeh <ahatamizadeh@nvidia.com>
> add swin unetr placeholder repository

- UNETR/BTCV/trainer.py
Signed-off-by: ahatamizadeh <ahatamizadeh@nvidia.com>
This PR enhances UNETR trainer and addresses #17.
> enhance unetr trainer

- .pre-commit-config.yaml
Signed-off-by: Wenqi Li <wenqil@nvidia.com>
> adds pre commit config

- .github/workflows/chatops.yml
Signed-off-by: Wenqi Li <wenqil@nvidia.com>
> adds formatter

- SkullRec/README.md
- SkullRec/pre_trained_weights/readme.md
- UNETR/BTCV/README.md
Signed-off-by: Wenqi Li <wenqil@nvidia.com>
> rename master -> main

- auto3dseg/algorithm_templates/dints/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/dints/configs/hyper_parameters_search.yaml
- auto3dseg/algorithm_templates/dints/configs/network.yaml
- auto3dseg/algorithm_templates/dints/configs/network_search.yaml
- auto3dseg/algorithm_templates/dints/scripts/search.py
- auto3dseg/algorithm_templates/dints/scripts/train.py
Signed-off-by: Dong Yang <dongy@dongy-mlt.client.nvidia.com>
> Updating dints config to distinguish training and searching hyper-parameters

- auto3dseg/algorithm_templates/dints/configs/network.yaml
- auto3dseg/algorithm_templates/dints/configs/network_search.yaml
- auto3dseg/algorithm_templates/dints/configs/transforms_train.yaml
- auto3dseg/algorithm_templates/dints/scripts/algo.py
- auto3dseg/algorithm_templates/dints/scripts/search.py
- auto3dseg/algorithm_templates/dints/scripts/train.py
- auto3dseg/algorithm_templates/segresnet/scripts/algo.py
- auto3dseg/algorithm_templates/segresnet/scripts/train.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/algo.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/train.py
- auto3dseg/algorithm_templates/swinunetr/scripts/algo.py
- auto3dseg/tests/test_algo_templates.py
> update fill config methods

- auto3dseg/algorithm_templates/dints/scripts/algo.py
- auto3dseg/algorithm_templates/segresnet/scripts/algo.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/algo.py
- auto3dseg/algorithm_templates/swinunetr/scripts/algo.py
- auto3dseg/tests/test_algo_templates.py
> ensure no memory address in fill_records and change to test all networks

- auto3dseg/algorithm_templates/dints/__init__.py
- auto3dseg/algorithm_templates/dints/scripts/algo.py
- auto3dseg/algorithm_templates/segresnet/__init__.py
- auto3dseg/algorithm_templates/segresnet/scripts/algo.py
- auto3dseg/algorithm_templates/segresnet2d/__init__.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/algo.py
- auto3dseg/algorithm_templates/swinunetr/__init__.py
- auto3dseg/algorithm_templates/swinunetr/scripts/algo.py
> add __init__.py and fix kwargs in algo.py

- auto3dseg/algorithm_templates/segresnet/scripts/algo.py
> fix segresnet multigpu bug

- auto3dseg/algorithm_templates/dints/configs/transforms_train.yaml
- auto3dseg/algorithm_templates/segresnet2d/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/segresnet2d/configs/transforms_train.yaml
Signed-off-by: dongyang0122 <don.yang.mech@gmail.com>
> Fixed minor issue caused by SpatialPadd and performance improvement

- auto3dseg/algorithm_templates/dints/scripts/algo.py
> fix param parsing for dints

- auto3dseg/algorithm_templates/segresnet/scripts/algo.py
Fix  https://github.com/Project-MONAI/MONAI/issues/5226
Signed-off-by: KumoLiu <yunl@nvidia.com>
> Fix list error in segresnet algo

- auto3dseg/algorithm_templates/dints/docs/README.md
- auto3dseg/algorithm_templates/segresnet2d/docs/README.md
Update README in Auto3DSeg algorithm templates of DiNTS and SegResNet2D
> Update README in Auto3DSeg Algorithm Templates

- .gitignore
- auto3dseg/README.md
- auto3dseg/algorithm_templates/dints/scripts/algo.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/algo.py
- auto3dseg/algorithm_templates/swinunetr/scripts/algo.py
- auto3dseg/tests/test_algo_templates.py
There are repeated issues reported on the CT-related transforms in the Auto3DSeg pipeline. This PR is trying to address them with fixes and new test to cover the CT cases.
To-do:
Issue Ref: 
https://github.com/Project-MONAI/tutorials/issues/965
https://github.com/Project-MONAI/MONAI/issues/5226
> Auto3DSeg CT Transforms and SwinUNETR fix

- auto3dseg/algorithm_templates/dints/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/dints/configs/hyper_parameters_search.yaml
- auto3dseg/algorithm_templates/segresnet2d/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/swinunetr/configs/hyper_parameters.yaml
- auto3dseg/tests/test_algo_templates.py
> fix issue 148

- auto3dseg/algorithm_templates/dints/scripts/algo.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/algo.py
- auto3dseg/algorithm_templates/swinunetr/scripts/algo.py
Signed-off-by: dongy <dongy@nvidia.com>
> Update auto3dseg algorithm algo.py

- auto3dseg/algorithm_templates/segresnet/scripts/algo.py
- auto3dseg/algorithm_templates/segresnet/scripts/segmenter.py
Segresnet algo updates
- small bug fix for single-gpu training
- added support for "sigmoid" with non-exclusive label classes
> Segresnet algo updates

- auto3dseg/algorithm_templates/dints/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/dints/configs/hyper_parameters_search.yaml
- auto3dseg/algorithm_templates/dints/scripts/algo.py
- auto3dseg/algorithm_templates/dints/scripts/dummy_runner.py
- auto3dseg/algorithm_templates/dints/scripts/search.py
- auto3dseg/algorithm_templates/dints/scripts/train.py
- auto3dseg/algorithm_templates/segresnet/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/segresnet/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet2d/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/segresnet2d/scripts/algo.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/dummy_runner.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/train.py
- auto3dseg/algorithm_templates/swinunetr/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/swinunetr/scripts/algo.py
- auto3dseg/algorithm_templates/swinunetr/scripts/dummy_runner.py
- auto3dseg/algorithm_templates/swinunetr/scripts/train.py
- auto3dseg/tests/test_algo_templates.py
Signed-off-by: dongy <dongy@nvidia.com>
> [auto3dseg] add num_works and cache_rate in config

- auto3dseg/algorithm_templates/dints/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/dints/scripts/infer.py
- auto3dseg/algorithm_templates/dints/scripts/validate.py
- auto3dseg/algorithm_templates/segresnet2d/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/segresnet2d/scripts/infer.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/validate.py
- auto3dseg/algorithm_templates/swinunetr/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/swinunetr/scripts/infer.py
- auto3dseg/algorithm_templates/swinunetr/scripts/validate.py
Correct typo in auto3dseg algorithm templates.
Signed-off-by: dongy <dongy@nvidia.com>
> Correct typo in auto3dseg

- auto3dseg/algorithm_templates/dints/scripts/search.py
- auto3dseg/algorithm_templates/dints/scripts/train.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/train.py
- auto3dseg/algorithm_templates/swinunetr/scripts/train.py
Signed-off-by: dongy <dongy@nvidia.com>
> Update training scripts in auto3dseg algorithm templates

- auto3dseg/algorithm_templates/dints/configs/hyper_parameters.yaml
Fix typo in config in auto3dseg templates.
> Fix typo in config in auto3dseg templates

- auto3dseg/algorithm_templates/dints/scripts/train.py
fixes https://github.com/Project-MONAI/MONAI/issues/6378
will this work @dongyang0122 ?
> replace to use native clip norm

- .github/workflows/integration.yml
closes https://github.com/Project-MONAI/research-contributions/issues/228
verified https://github.com/Project-MONAI/research-contributions/actions/runs/4734178601/jobs/8402730770
> 228 - update integration tests

- auto3dseg/algorithm_templates/dints/scripts/train.py
from the previous https://github.com/Project-MONAI/research-contributions/commit/d8bec423e3b3ece41fca6589f4cf7d4502635c57
fixes https://github.com/Project-MONAI/MONAI/issues/6391
> recommit PolynomialLR

- auto3dseg/algorithm_templates/dints/scripts/train.py
- auto3dseg/algorithm_templates/segresnet/scripts/segmenter.py
- auto3dseg/algorithm_templates/swinunetr/scripts/train.py
fixes #234 
fixes #235
requires https://github.com/Project-MONAI/MONAI/pull/6399
> Fixes auto3dseg integration 234 235

- auto3dseg/algorithm_templates/segresnet/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/segresnet/scripts/algo.py
- auto3dseg/algorithm_templates/segresnet/scripts/infer.py
- auto3dseg/algorithm_templates/segresnet/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet/scripts/utils.py
- adds logging via logger.debug(), instead of print()
- adds tqdm for progress
> SegResNet algo add logging

- auto3dseg/algorithm_templates/segresnet/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/algo.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/segmenter_2d.py
> Segresnet cleanup

- auto3dseg/algorithm_templates/segresnet/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/segresnet/scripts/algo.py
- auto3dseg/algorithm_templates/segresnet/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet2d/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/segresnet2d/scripts/segmenter.py
> Segres algo fixes

- auto3dseg/algorithm_templates/segresnet/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/segresnet/scripts/algo.py
- auto3dseg/algorithm_templates/segresnet/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet/scripts/utils.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/algo.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/segmenter_2d.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/utils.py
bug fixes, and performance improvements
> Segresnet algo update

- auto3dseg/algorithm_templates/segresnet/scripts/algo.py
- auto3dseg/algorithm_templates/segresnet/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/algo.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/segmenter_2d.py
segresnet performance improvements
> segresnet improvements 

- auto3dseg/algorithm_templates/segresnet/scripts/infer.py
- auto3dseg/algorithm_templates/segresnet/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet/scripts/validate.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/infer.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/validate.py
Segresnet algo update to re-save input config with auto adjustments upon training.
> Segresnet algo update to re-save input config.

- auto3dseg/algorithm_templates/dints/configs/transforms_train.yaml
- auto3dseg/algorithm_templates/segresnet/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/segmenter_2d.py
- auto3dseg/algorithm_templates/swinunetr/configs/transforms_train.yaml
remove the relevant API calls, keep the config flags for future implementation
> remove lazy resampling feature

- auto3dseg/algorithm_templates/segresnet/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/segmenter_2d.py
Segres algo, skip DDP init in inference
> Segres algo, skip DDP init in inference

- auto3dseg/algorithm_templates/dints/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/dints/configs/transforms_train.yaml
- auto3dseg/algorithm_templates/dints/configs/transforms_validate.yaml
- auto3dseg/algorithm_templates/dints/scripts/algo.py
- auto3dseg/algorithm_templates/dints/scripts/search.py
- auto3dseg/algorithm_templates/dints/scripts/train.py
- auto3dseg/algorithm_templates/dints/scripts/validate.py
- auto3dseg/algorithm_templates/swinunetr/scripts/algo.py
- auto3dseg/algorithm_templates/swinunetr/scripts/train.py
- auto3dseg/algorithm_templates/swinunetr/scripts/validate.py
Implemented incremental modifications to the DiNTS algorithm:
1. Minimized CPU RAM consumptions during the training process of the DiNTS model;
2. Implemented a label conversion feature to accommodate users with varying label formats;
> auto3dseg - algorithm updates

- auto3dseg/algorithm_templates/segresnet/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet2d/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/segresnet2d/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/segmenter_2d.py
> remove mentions of lazy resampling

- auto3dseg/algorithm_templates/dints/scripts/algo.py
- auto3dseg/algorithm_templates/dints/scripts/train.py
- auto3dseg/algorithm_templates/dints/scripts/validate.py
- auto3dseg/algorithm_templates/segresnet/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/segmenter.py
Addressed minor issues in algorithm templates:
- Resolved issues encountered within the DiNTS validation script;
- Incorporated label conversion support into the DiNTS validation script;
- Refined the validation data loader configuration to enhance efficiency.
> [auto3dseg] Resolved issues encountered within the DiNTS validation script

- auto3dseg/algorithm_templates/dints/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/dints/docs/README.md
- auto3dseg/algorithm_templates/dints/scripts/search.py
- auto3dseg/algorithm_templates/dints/scripts/train.py
- auto3dseg/algorithm_templates/dints/scripts/validate.py
Implemented minor revision to the DiNTS algorithm:
- Updated the README document;
- Incorporated support for various options of training/validation keys.
> [auto3dseg] Implemented minor revisions to the DiNTS algorithm

- auto3dseg/algorithm_templates/dints/configs/hyper_parameters_search.yaml
- auto3dseg/algorithm_templates/dints/scripts/infer.py
- auto3dseg/algorithm_templates/dints/scripts/search.py
- auto3dseg/algorithm_templates/dints/scripts/train.py
- auto3dseg/algorithm_templates/dints/scripts/validate.py
- auto3dseg/algorithm_templates/swinunetr/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/swinunetr/configs/transforms_train.yaml
- auto3dseg/algorithm_templates/swinunetr/docs/README.md
- auto3dseg/algorithm_templates/swinunetr/scripts/algo.py
- auto3dseg/algorithm_templates/swinunetr/scripts/infer.py
- auto3dseg/algorithm_templates/swinunetr/scripts/train.py
- auto3dseg/algorithm_templates/swinunetr/scripts/validate.py
Optimized the SwinUNETR algorithm template:
- Updated the README document;
- Updated the data type and the validation dataloader;
- Rectified the errors in DiNTS's sigmoid formulation;
- Resolved issues encountered during label conversion in the DiNTS validation process at the original spacing;
- Incorporated support for label conversion into the SwinUNETR algorithm;
- Rectified a minor error present in the validation script of the SwinUNETR algorithm;
- Refined inference scripts for both DiNTS and SwinUNETR;
- Refined architecture search scripts for DiNTS.
> [auto3dseg] Optimized the SwinUNETR algorithm to enhance operational efficiency

- .github/workflows/chatops.yml
- .github/workflows/integration.yml
- .github/workflows/packaging-algo.yml
tested:
- https://github.com/Project-MONAI/research-contributions/actions/runs/5229856553/jobs/9443093916
outcome:
- https://github.com/Project-MONAI/MONAI/pull/6600
> change algo template hash in monai core automatically after release

- .github/workflows/integration.yml
fixes https://github.com/Project-MONAI/research-contributions/issues/274
config verified https://github.com/Project-MONAI/research-contributions/actions/runs/5360590191/jobs/9725646128
> 274 update ci tests config

- auto3dseg/algorithm_templates/segresnet/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/segmenter.py
> Segres algo typo

- auto3dseg/algorithm_templates/dints/scripts/infer.py
- auto3dseg/algorithm_templates/dints/scripts/train.py
- auto3dseg/algorithm_templates/dints/scripts/validate.py
Refine dints algorithm template.
> [auto3dseg] refine dints template

- auto3dseg/algorithm_templates/dints/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/dints/scripts/infer.py
- auto3dseg/algorithm_templates/dints/scripts/train.py
- auto3dseg/algorithm_templates/dints/scripts/validate.py
Refine DiNTS algorithm template.
- Enhance the efficiency of DiNTS model training.
- Additionally, incorporated a new functionality that permits users to fine-tune pre-existing checkpoints. This provides them with the options to modify any training components - for instance, hyper-parameters, loss, optimizer, and so forth - exclusively by altering the JSON configuration file.
> [auto3dseg] refine DiNTS algorithm template

- auto3dseg/algorithm_templates/dints/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/dints/scripts/infer.py
- auto3dseg/algorithm_templates/dints/scripts/train.py
- auto3dseg/algorithm_templates/dints/scripts/validate.py
Reverts Project-MONAI/research-contributions#283
> Revert "[auto3dseg] refine DiNTS algorithm template"

- auto3dseg/algorithm_templates/dints/scripts/infer.py
- auto3dseg/algorithm_templates/dints/scripts/search.py
- auto3dseg/algorithm_templates/dints/scripts/train.py
- auto3dseg/algorithm_templates/dints/scripts/validate.py
- auto3dseg/algorithm_templates/segresnet/scripts/utils.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/utils.py
- auto3dseg/algorithm_templates/swinunetr/scripts/train.py
```
[2023-09-21T18:21:43.805Z]     raise v
[2023-09-21T18:21:43.805Z]   File "/usr/lib/python3.10/logging/config.py", line 392, in resolve
[2023-09-21T18:21:43.805Z]     self.importer(used)
[2023-09-21T18:21:43.805Z] ValueError: Cannot resolve '__main__.RankFilter': No module named '__main__.RankFilter'; '__main__' is not a package
```
> fixes rank filter

- auto3dseg/README.md
cc @mingxin-zheng @dongyang0122 @myron
> Update auto3dseg README.md about testing

- .github/workflows/packaging-algo.yml
since https://github.com/Project-MONAI/MONAI/pull/7084
> algo hash in monai/utils/misc.py

- auto3dseg/algorithm_templates/dints/scripts/search.py
- auto3dseg/algorithm_templates/dints/scripts/train.py
Enable mlflow for metric tracking in algorithms.
> [auto3dseg] enable mlflow in algorithms

- auto3dseg/README.md
- auto3dseg/metadata.json
Address #324 
This PR adds a `metadata.json` file in the `auto3dseg` folder, and it is used to record the version and changelog.
The initial version is set to `0.0.1` which covers the changes of commit: 03a6d4effb9223670f439c3a29198ef34938922f
After the PR is merged, everytime the `auto3dseg` folder is changed, this file should also be changed.
> Add metadata for auto3dseg

- auto3dseg/algorithm_templates/dints/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/dints/configs/hyper_parameters_search.yaml
- auto3dseg/algorithm_templates/dints/configs/transforms_infer.yaml
- auto3dseg/algorithm_templates/dints/configs/transforms_train.yaml
- auto3dseg/algorithm_templates/dints/configs/transforms_validate.yaml
- auto3dseg/algorithm_templates/dints/scripts/algo.py
- auto3dseg/algorithm_templates/dints/scripts/dummy_runner.py
- auto3dseg/algorithm_templates/dints/scripts/infer.py
- auto3dseg/algorithm_templates/dints/scripts/search.py
- auto3dseg/algorithm_templates/dints/scripts/train.py
- auto3dseg/algorithm_templates/dints/scripts/validate.py
- auto3dseg/metadata.json
Update hyper-parameter naming in dints algorithm templates.
> Update hyper-parameter naming in dints algorithm templates.

- auto3dseg/algorithm_templates/dints/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/dints/scripts/algo.py
- auto3dseg/algorithm_templates/dints/scripts/search.py
- auto3dseg/algorithm_templates/dints/scripts/train.py
Update mlflow support for cloud service.
> [Auto3DSeg] Update mlflow support

- auto3dseg/algorithm_templates/dints/scripts/algo.py
Minor updates on algorithm template (dints) in order to pass all integration tests.
> [Auto3DSeg] Minor update algorithm template

- auto3dseg/README.md
- auto3dseg/algorithm_templates/segresnet/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/segresnet/scripts/algo.py
- auto3dseg/algorithm_templates/segresnet/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet2d/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/segresnet2d/scripts/algo.py
- auto3dseg/algorithm_templates/segresnet2d/scripts/segmenter.py
- auto3dseg/metadata.json
> segresnet mlflow support

- auto3dseg/algorithm_templates/segresnet/configs/hyper_parameters.yaml
- auto3dseg/algorithm_templates/segresnet/scripts/segmenter.py
- auto3dseg/algorithm_templates/segresnet/scripts/utils.py
Misc updates and fixes for segresnet algo
- support for various augmentation modes
- by default transform all input images to RAS orientation (with option to disable)
- option to cache images in int16 in RAM
- improved random crop in multi-label tasks (with sigmoid) to account for background class
- option to save output probability maps
- Bug fix for output inference with softmax, inplace softmax had incorrect results / unreliable.  
- Bug fix for softmax giving different results in float(), using double()
> Segresnet algo updates and bugfixes

- auto3dseg/algorithm_templates/swinunetr/scripts/train.py
- auto3dseg/configs/metadata.json
To avoid occationally appeared github download issue
> Update swin unetr weights url for auto3dseg template

- auto3dseg/algorithm_templates/swinunetr/scripts/train.py
> Fix FileNotFoundError in swinunetr

- auto3dseg/algorithm_templates/swinunetr/scripts/train.py
> Add timeout in swinunetr algo

- auto3dseg/algorithm_templates/dints/scripts/infer.py
> Fix multiprocess writing issue in dints

- auto3dseg/algorithm_templates/swinunetr/scripts/infer.py
- auto3dseg/algorithm_templates/swinunetr/scripts/train.py
- auto3dseg/algorithm_templates/swinunetr/scripts/validate.py
> Fix AttributeError: 'NoneType' object has no attribute 'items' in swinunetr

- auto3dseg/algorithm_templates/dints/scripts/train.py
Solving issue from MONAI repository: [#8352](https://github.com/Project-MONAI/MONAI/issues/8352)
> Corrects pytorch_after import path

- .github/workflows/packaging-algo.yml
based on: https://github.com/Project-MONAI/research-contributions/actions/runs/13673133711/job/38227583606
> Fix workflow
